/**
 * build-tokens.ts — the token GENERATOR (file 08 §2/§6). Emits the two committed build
 * artifacts from the canonical ../tokens.ts source:
 *   - tokens.json : the flat export the `prom` CLI ANSI-16 resolver + the Monaco
 *                   theme-gen read (file 08 §8 / §5.7).
 *   - tokens.css  : the CSS variables for [data-theme] (dark/light/high-contrast) and
 *                   [data-density] (comfortable/compact) — the runtime contract every
 *                   component (Tailwind utility OR plain CSS var) consumes.
 * Run: node --import ../../apps/cli/dev-register.mjs packages/ui/src/tokens/build-tokens.ts
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  darkSemantic,
  density,
  elevation,
  highContrastSemantic,
  lightSemantic,
  motion,
  radius,
  space,
  typography,
} from "../tokens.js";

const here = dirname(fileURLToPath(import.meta.url));

const themes = {
  dark: darkSemantic,
  light: lightSemantic,
  "high-contrast": highContrastSemantic,
} as const;

const tokensJson = {
  $schema: "prometheus-tokens/1",
  themes,
  space,
  radius,
  elevation,
  density,
  typography,
};
writeFileSync(join(here, "tokens.json"), `${JSON.stringify(tokensJson, null, 2)}\n`);

let css = "/* GENERATED by tokens/build-tokens.ts — do not edit by hand.\n";
css += "   Source of truth: packages/ui/src/tokens.ts (file 08 §2). */\n\n";
for (const [name, sem] of Object.entries(themes)) {
  const sel = name === "dark" ? `:root,\n[data-theme="dark"]` : `[data-theme="${name}"]`;
  css += `${sel} {\n`;
  for (const [k, v] of Object.entries(sem)) css += `  --${k}: ${v};\n`;
  css += "}\n\n";
}
for (const [name, d] of Object.entries(density)) {
  css += `[data-density="${name}"] {\n`;
  for (const [k, v] of Object.entries(d)) css += `  --${k}: ${v};\n`;
  css += "}\n\n";
}

// Scale tokens (space / radius / type / font / motion) as CSS vars on :root — the
// vendored primitives reference these (--space-N, --radius-md, --text-body-size,
// --font-ui/--font-mono, --motion-*); emitting them makes the inline fallbacks moot.
css += ":root {\n";
for (const [k, val] of Object.entries(space)) css += `  --space-${k}: ${val};\n`;
for (const [k, val] of Object.entries(radius)) css += `  --radius-${k}: ${val};\n`;
for (const [k, val] of Object.entries(elevation)) css += `  --elevation-${k}: ${val};\n`;
css += `  --font-ui: ${typography.fontUi};\n`;
css += `  --font-mono: ${typography.fontMono};\n`;
css += `  --font-brand: ${typography.fontBrand};\n`;
// The brand wordmark treatment (08 §2.3: ui weight 600, -0.01em tracking, lowercase).
css += `  --font-brand-weight: ${typography.weight.semibold};\n`;
css += `  --font-brand-tracking: ${typography.brandLetterSpacing};\n`;
// The weight scale (08 §2.3: 400 body · 500 labels/headers · 600 titles/active-nav/CTA).
for (const [k, v] of Object.entries(typography.weight)) css += `  --font-weight-${k}: ${v};\n`;
for (const [k, s] of Object.entries(typography.scale)) {
  css += `  --text-${k}-size: ${s.size};\n`;
  css += `  --text-${k}-line: ${s.line};\n`;
}
css += `  --motion-hover: ${motion.hover};\n`;
css += `  --motion-panel: ${motion.panel};\n`;
css += `  --motion-route: ${motion.route};\n`;
css += `  --motion-easing: ${motion.easing};\n`;
css += "}\n\n";

// The brand wordmark utility (08 §2.3: lowercase "prometheus", weight 600, -0.01em).
css += ".prom-wordmark {\n";
css += "  font-family: var(--font-brand);\n";
css += "  font-weight: var(--font-brand-weight);\n";
css += "  letter-spacing: var(--font-brand-tracking);\n";
css += "  text-transform: lowercase;\n}\n\n";

// Component animations the primitives reference by class (Skeleton shimmer, the
// indeterminate Progress sweep) + the §7 reduced-motion reset (collapse to 0ms).
css += "@keyframes prom-skeleton-shimmer {\n";
css += "  0% {\n    opacity: 0.6;\n  }\n";
css += "  50% {\n    opacity: 1;\n  }\n";
css += "  100% {\n    opacity: 0.6;\n  }\n}\n\n";
css += ".prom-skeleton {\n";
css += "  animation: prom-skeleton-shimmer 1.4s ease-in-out infinite;\n}\n\n";
css += "@keyframes prom-progress-sweep {\n";
css += "  0% {\n    transform: translateX(-120%);\n  }\n";
css += "  100% {\n    transform: translateX(320%);\n  }\n}\n\n";
css += ".prom-progress-indeterminate {\n";
css += "  animation: prom-progress-sweep 1.1s ease-in-out infinite;\n}\n\n";
// 08 §7 / §2.5: prefers-reduced-motion → 0ms transitions + no looping animation.
css += "@media (prefers-reduced-motion: reduce) {\n";
css += "  *,\n  *::before,\n  *::after {\n";
css += "    animation-duration: 0.01ms !important;\n";
css += "    animation-iteration-count: 1 !important;\n";
css += "    transition-duration: 0.01ms !important;\n";
css += "  }\n}\n";

writeFileSync(join(here, "tokens.css"), css);

console.log("wrote tokens.json + tokens.css");
